### ISSUE TITLE
/ is shown as ? onscreen

### ISSUE THREAD

**Issue by BeeVee23** [Phaiax/Key-n-Stroke#109]
Hi,
I've noticed that the forward slash (/) is shown as a question mark (?) when pressed. The ? is the key I get when I press Shift / in my keymap (UK), but I don't get a similar issue with any other punctuation, only slash. 

You have created a great tool!

**Comment by BeeVee23** [comment]
Backslash (\) is also shown as Vertical Pipe (|) on my UK keyboard

**Comment by ckelwin** [comment]
@BeeVee23 @Phaiax This issue is fixed in this PR: https://github.com/Phaiax/Key-n-Stroke/pull/88

**Comment by BeeVee23** [comment]
The most recent build is still dated for 2022 and I still have the problem.

**Comment by BeeVee23** [comment]
Fantastic, thank you. I'd like to also send you a contribution, but I don't use PayPal nor have any bitcoin.

All the best,
--

Ben Vost

Skype: BeeVee_at_work

Web: https://benvost.fr

Mobile/Portable: +33 628 51 56 43




---- On Fri, 26 Apr 2024 17:32:24 +0200 ***@***.*** wrote ----



Hi. I will make a new build for this. Should be available this weekend or next weekend :)


Am 26. April 2024 09:43:34 MESZ schrieb BeeVee23 ***@***.***>:

**Comment by Phaiax** [comment]
It will take a few more days. I thought issuing a new certificate would be quick, but it seems I need to go through the whole verification process again.

**Comment by BeeVee23** [comment]
Thanks for continuing to try :)

-- 

Ben Vost

Skype: BeeVee_at_work

Web: https://benvost.fr

Mobile/Portable: +33 628 51 56 43








---- On Mon, 06 May 2024 21:32:06 +0200 Phaiax ***@***.***> wrote ---





It will take a few more days. I thought issuing a new certificate would be quick, but it seems I need to go through the whole verification process again.

**Comment by BeeVee23** [comment]
Any update on progress, or how else I could contribute other than PayPal or bitcoin?

B

**Comment by sherkhan30452** [comment]
Hi, any updates regarding this? Getting download option for 1.1.0

**Comment by BeeVee23** [comment]
Hi Phaiax,
It has been a month and a half since you said it would take a few more days. Can I send you some money to expedite this? I don't want to send crypto.

All the best,

**B**
